#import <PonyDebugger/PDObject.h>
#import <PonyDebugger/PDDebugger.h>
#import <PonyDebugger/PDDynamicDebuggerDomain.h>


@class PDCSSCSSStyle;
@class PDCSSSourceRange;


// This object identifies a CSS style in a unique way.
@interface PDCSSCSSStyleId : PDObject

// Enclosing stylesheet identifier.
@property (nonatomic, retain) NSString *styleSheetId;

// The style ordinal within the stylesheet.
// Type: integer
@property (nonatomic, retain) NSNumber *ordinal;

@end


// This object identifies a CSS rule in a unique way.
@interface PDCSSCSSRuleId : PDObject

// Enclosing stylesheet identifier.
@property (nonatomic, retain) NSString *styleSheetId;

// The rule ordinal within the stylesheet.
// Type: integer
@property (nonatomic, retain) NSNumber *ordinal;

@end


// CSS rule collection for a single pseudo style.
@interface PDCSSPseudoIdRules : PDObject

// Pseudo style identifier (see <code>enum PseudoId</code> in <code>RenderStyleConstants.h</code>).
// Type: integer
@property (nonatomic, retain) NSNumber *pseudoId;

// CSS rules applicable to the pseudo style.
// Type: array
@property (nonatomic, retain) NSArray *rules;

@end


// CSS rule collection for a single pseudo style.
@interface PDCSSInheritedStyleEntry : PDObject

// The ancestor node's inline style, if any, in the style inheritance chain.
@property (nonatomic, retain) PDCSSCSSStyle *inlineStyle;

// CSS rules matching the ancestor node in the style inheritance chain.
// Type: array
@property (nonatomic, retain) NSArray *matchedCSSRules;

@end


// CSS style information for a DOM style attribute.
@interface PDCSSCSSStyleAttribute : PDObject

// DOM attribute name (e.g. "width").
// Type: string
@property (nonatomic, retain) NSString *name;

// CSS style generated by the respective DOM attribute.
@property (nonatomic, retain) PDCSSCSSStyle *style;

@end


// CSS stylesheet metainformation.
@interface PDCSSCSSStyleSheetHeader : PDObject

// The stylesheet identifier.
@property (nonatomic, retain) NSString *styleSheetId;

// Stylesheet resource URL.
// Type: string
@property (nonatomic, retain) NSString *sourceURL;

// Stylesheet title.
// Type: string
@property (nonatomic, retain) NSString *title;

// Denotes whether the stylesheet is disabled.
// Type: boolean
@property (nonatomic, retain) NSNumber *disabled;

@end


// CSS stylesheet contents.
@interface PDCSSCSSStyleSheetBody : PDObject

// The stylesheet identifier.
@property (nonatomic, retain) NSString *styleSheetId;

// Stylesheet resource URL.
// Type: array
@property (nonatomic, retain) NSArray *rules;

// Stylesheet resource contents (if available).
// Type: string
@property (nonatomic, retain) NSString *text;

@end


// CSS rule representation.
@interface PDCSSCSSRule : PDObject

// The CSS rule identifier (absent for user agent stylesheet and user-specified stylesheet rules).
@property (nonatomic, retain) PDCSSCSSRuleId *ruleId;

// Rule selector.
// Type: string
@property (nonatomic, retain) NSString *selectorText;

// Parent stylesheet resource URL (for regular rules).
// Type: string
@property (nonatomic, retain) NSString *sourceURL;

// Line ordinal of the rule selector start character in the resource.
// Type: integer
@property (nonatomic, retain) NSNumber *sourceLine;

// The parent stylesheet type: "user" for user stylesheets, "user-agent" for user-agent stylesheets, "inspector" for stylesheets created by the inspector (i.e. those holding new rules created with <code>addRule()</code>), "regular" for regular stylesheets.
// Type: string
@property (nonatomic, retain) NSString *origin;

// Associated style declaration.
@property (nonatomic, retain) PDCSSCSSStyle *style;

// The rule selector range in the underlying resource (if available).
@property (nonatomic, retain) PDCSSSourceRange *selectorRange;

// Media list array (for rules involving media queries). The array enumerates media queries starting with the innermost one, going outwards.
// Type: array
@property (nonatomic, retain) NSArray *media;

@end


// Text range within a resource.
@interface PDCSSSourceRange : PDObject

// Start of range (inclusive).
// Type: integer
@property (nonatomic, retain) NSNumber *start;

// End of range (exclusive).
// Type: integer
@property (nonatomic, retain) NSNumber *end;

@end


@interface PDCSSCSSComputedStyleProperty : PDObject

// Computed style property name.
// Type: string
@property (nonatomic, retain) NSString *name;

// Computed style property value.
// Type: string
@property (nonatomic, retain) NSString *value;

@end


// CSS style representation.
@interface PDCSSCSSStyle : PDObject

// The CSS style identifier (absent for attribute styles).
@property (nonatomic, retain) PDCSSCSSStyleId *styleId;

// CSS properties in the style.
// Type: array
@property (nonatomic, retain) NSArray *cssProperties;

// Computed values for all shorthands found in the style.
// Type: array
@property (nonatomic, retain) NSArray *shorthandEntries;

// Style declaration text (if available).
// Type: string
@property (nonatomic, retain) NSString *cssText;

// Style declaration range in the enclosing stylesheet (if available).
@property (nonatomic, retain) PDCSSSourceRange *range;

// The effective "width" property value from this style.
// Type: string
@property (nonatomic, retain) NSString *width;

// The effective "height" property value from this style.
// Type: string
@property (nonatomic, retain) NSString *height;

@end


// CSS style effective visual dimensions and source offsets.
@interface PDCSSCSSProperty : PDObject

// The property name.
// Type: string
@property (nonatomic, retain) NSString *name;

// The property value.
// Type: string
@property (nonatomic, retain) NSString *value;

// The property priority (implies "" if absent).
// Type: string
@property (nonatomic, retain) NSString *priority;

// Whether the property is implicit (implies <code>false</code> if absent).
// Type: boolean
@property (nonatomic, retain) NSNumber *implicit;

// The full property text as specified in the style.
// Type: string
@property (nonatomic, retain) NSString *text;

// Whether the property is understood by the browser (implies <code>true</code> if absent).
// Type: boolean
@property (nonatomic, retain) NSNumber *parsedOk;

// The property status: "active" (implied if absent) if the property is effective in the style, "inactive" if the property is overridden by a same-named property in this style later on, "disabled" if the property is disabled by the user, "style" if the property is reported by the browser rather than by the CSS source parser.
// Type: string
@property (nonatomic, retain) NSString *status;

// The related shorthand property name (absent if this property is not a longhand).
// Type: string
@property (nonatomic, retain) NSString *shorthandName;

// The entire property range in the enclosing style declaration (if available).
@property (nonatomic, retain) PDCSSSourceRange *range;

@end


// CSS media query descriptor.
@interface PDCSSCSSMedia : PDObject

// Media query text.
// Type: string
@property (nonatomic, retain) NSString *text;

// Source of the media query: "mediaRule" if specified by a @media rule, "importRule" if specified by an @import rule, "linkedSheet" if specified by a "media" attribute in a linked stylesheet's LINK tag, "inlineSheet" if specified by a "media" attribute in an inline stylesheet's STYLE tag.
// Type: string
@property (nonatomic, retain) NSString *source;

// URL of the document containing the media query description.
// Type: string
@property (nonatomic, retain) NSString *sourceURL;

// Line in the document containing the media query (not defined for the "stylesheet" source).
// Type: integer
@property (nonatomic, retain) NSNumber *sourceLine;

@end


// CSS selector profile entry.
@interface PDCSSSelectorProfileEntry : PDObject

// CSS selector of the corresponding rule.
// Type: string
@property (nonatomic, retain) NSString *selector;

// URL of the resource containing the corresponding rule.
// Type: string
@property (nonatomic, retain) NSString *url;

// Selector line number in the resource for the corresponding rule.
// Type: integer
@property (nonatomic, retain) NSNumber *lineNumber;

// Total time this rule handling contributed to the browser running time during profiling (in milliseconds.)
// Type: number
@property (nonatomic, retain) NSNumber *time;

// Number of times this rule was considered a candidate for matching against DOM elements.
// Type: integer
@property (nonatomic, retain) NSNumber *hitCount;

// Number of times this rule actually matched a DOM element.
// Type: integer
@property (nonatomic, retain) NSNumber *matchCount;

@end


@interface PDCSSSelectorProfile : PDObject

// Total processing time for all selectors in the profile (in milliseconds.)
// Type: number
@property (nonatomic, retain) NSNumber *totalTime;

// CSS selector profile entries.
// Type: array
@property (nonatomic, retain) NSArray *data;

@end


